### PR TITLE
Null Safety

### PR DESCRIPTION
**Pull request by fareesh**

### CODE REVIEW

**Comment by rlazom** [comment]
This will solve issue #22

**Comment by nipunasudha** [comment]
Thank you very much for this PR @fareesh hope this will be merged soon

**Comment by vjrj** [comment]
@fareesh , can you make the customBuilder nullable in `types.dart`
```
/// Builder for custom choice item
typedef Widget? C2Builder<T>(C2Choice<T> item);
```
This is useful for build only some items with a custom builder and use the default one in the rest. See the All chip in:
https://raw.github.com/living-atlases/la-toolkit/dev/screenshots/s16.png

TIA

**Comment by nipunasudha** [comment]
Could you please give an update about the status of this PR?

**Comment by NarHakobyan** [comment]
Hey, tried to run forked code and got warning.

```
widget.dart:211:19: Warning: Operand of null-aware operation '??' has type 'List<T>' which excludes null.
 - 'List' is from 'dart:core'.
        _values = value ?? [],
                  ^
```

**Comment by rlazom** [comment]
Indeed, you are right, the _migrate tool_ do all the heavy work, but the code still needs to be reviewed.

In this particular case, were the variables have "null safety" doesn't make sense this:
`_values = value ?? []`
so, it should be just:
`_values = value`

I hope this helps 😎👍

**Comment by nipunasudha** [comment]
Anyone considering merging this?

**Comment by nipunasudha** [comment]
This was 25 days ago, PLEASE merge this

**Comment by NarHakobyan** [comment]
I removed this lib because of it's not maintainable

**Comment by vjrj** [comment]
Try this other: https://github.com/davigmacode/flutter_chips_choice/pull/25

**Review by aasif1297 — APPROVED** [review]

**Comment by tehsunnliu** [comment]
When will this be merged and published?

**Comment by davigmacode** [comment]
Hi everyone,

I'm sorry to announce that I'm no longer maintaining the [chips_choice](https://pub.dev/packages/chips_choice) package. It's been a great project, but it's become too difficult to maintain.

In its place, I've released a new package called [choice](https://pub.dev/packages/choice). The combination to [smart_select](https://pub.dev/packages/smart_select) and [chips_choice](https://pub.dev/packages/chips_choice) with cleaner, more flexible, and composable API for creating inline or prompted choice widgets with single or multiple selection.

I hope you'll check out [choice](https://pub.dev/packages/choice). I think you'll find it to be a great replacement for [chips_choice](https://pub.dev/packages/chips_choice).

Thanks for your understanding.

**Pull request closed without merging**
